{% set name = "openff-utilities" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-utilities/archive/v{{ version }}.tar.gz
  sha256: d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed
  patches:
    - patches/version-star-import.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - importlib_resources

test:
  requires:
    - python {{ python_min }}
  imports:
    - openff.utilities
  commands:
    - python -c "from openff.utilities import *"

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of miscellaneous utility functions used by experimental OpenFF packages
  dev_url: https://github.com/openforcefield/openff-utilities

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
