{% set name = "openff-utilities" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-utilities/archive/v{{ version }}.tar.gz
  sha256: 1cd85adfc6165f78e4f5c2e2b6c9804b1b5863094cb842592cc2aaeacd91ca44

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python <3.12
    - pip
  run:
    - python >=3.9
    - importlib_resources

test:
  imports:
    - openff.utilities
  commands:
    - python -c "from openff.utilities import *"

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of miscellaneous utility functions used by experimental OpenFF packages
  dev_url: https://github.com/openforcefield/openff-utilities

extra:
  recipe-maintainers:
    - mattwthompson
